src/Entity/DeptEmp.php
<?php

namespace App\Entity;

use App\Repository\DeptEmpRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=DeptEmpRepository::class)
 * @ORM\Table(name="dept_emp")
 */
class DeptEmp
{
	use DateIntervalTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;


	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\Employee", inversedBy="empNo")
	 * @ORM\JoinColumn(nullable=false, name="emp_no", referencedColumnName="emp_no", onDelete="CASCADE")
	 * @Assert\NotBlank()
	 */
	private $empNo;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\Department", inversedBy="deptNo")
	 * @ORM\JoinColumn(nullable=false, name="dept_no", referencedColumnName="dept_no", onDelete="CASCADE")
	 * @Assert\NotBlank()
	 */
	private $deptNo;

    public function getId(): ?int
    {
        return $this->id;
    }


	public function getEmpNo(): ?employee
	{
		return $this->empNo;
	}

	public function setEmpNo(?employee $empNo): self
	{
		$this->empNo = $empNo;

		return $this;
	}


	public function getDeptNo(): ?department
	{
		return $this->deptNo;
	}

	public function setDeptNo(?department $deptNo): self
	{
		$this->deptNo = $deptNo;

		return $this;
	}
}

src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EmployeeRepository::class)
 * @ORM\Table(name="employees")
 * @UniqueEntity(fields="empNo", message="This employee id is in use")
 */
class Employee
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer", name="emp_no")
     * @Assert\Length(min=1)
	 */
    private $empNo;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=14, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=1, nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $hireDate;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Title", mappedBy="empNo")
     */
    private $titles;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Salary", mappedBy="empNo")
	 */
	private $salaries;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\DeptEmp", mappedBy="empNo")
	 */
	private $deptEmps;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\DeptManager", mappedBy="empNo")
	 */
	private $deptManagers;

    public function __construct()
    {
        $this->titles = new ArrayCollection();
        $this->salaries = new ArrayCollection();
        $this->deptEmps = new ArrayCollection();
        $this->deptManagers = new ArrayCollection();
    }

    public function getEmpNo(): ?int
    {
        return $this->empNo;
    }

    public function setEmpNo(int $empNo): self
    {
        $this->empNo = $empNo;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getHireDate(): ?\DateTimeInterface
    {
        return $this->hireDate;
    }

    public function setHireDate(?\DateTimeInterface $hireDate): self
    {
        $this->hireDate = $hireDate;

        return $this;
    }

    /**
     * @return Collection|Title[]
     */
    public function getTitles(): Collection
    {
        return $this->titles;
    }

    public function addTitle(Title $title): self
    {
        if (!$this->titles->contains($title)) {
            $this->titles[] = $title;
            $title->setEmpNo($this);
        }

        return $this;
    }

    public function removeTitle(Title $title): self
    {
        if ($this->titles->removeElement($title)) {
            // set the owning side to null (unless already changed)
            if ($title->getEmpNo() === $this) {
                $title->setEmpNo(null);
            }
        }

        return $this;
    }

	/**
	 * @return Collection|Salary[]
	 */
	public function getSalaries(): Collection
	{
		return $this->salaries;
	}

	public function addSalary(Salary $salary): self
	{
		if (!$this->salaries->contains($salary)) {
			$this->salaries[] = $salary;
			$salary->setEmpNo($this);
		}

		return $this;
	}

	public function removeSalary(Salary $salary): self
	{
		if ($this->salaries->removeElement($salary)) {
			// set the owning side to null (unless already changed)
			if ($salary->getEmpNo() === $this) {
				$salary->setEmpNo(null);
			}
		}

		return $this;
	}

		public function getFullName()
	{
		return $this->getFirstName().' '.$this->getLastName();
	}

	/**
	 * @return Collection|DeptEmp[]
	 */
	public function getDeptEmps(): Collection
	{
		return $this->deptEmps;
	}

	public function addDeptEmp(DeptEmp $deptEmp): self
	{
		if (!$this->deptEmps->contains($deptEmp)) {
			$this->deptEmps[] = $deptEmp;
			$deptEmp->setEmpNo($this);
		}

		return $this;
	}

	public function removeDeptEmp(DeptEmp $deptEmp): self
	{
		if ($this->deptEmps->removeElement($deptEmp)) {
			// set the owning side to null (unless already changed)
			if ($deptEmp->getEmpNo() === $this) {
				$deptEmp->setEmpNo(null);
			}
		}

		return $this;
	}


	/**
	 * @return Collection|DeptManager[]
	 */
	public function getDeptManagers(): Collection
	{
		return $this->deptManagers;
	}

	public function addDeptManager(DeptManager $deptManager): self
	{
		if (!$this->deptManagers->contains($deptManager)) {
			$this->deptManagers[] = $deptManager;
			$deptManager->setEmpNo($this);
		}

		return $this;
	}

	public function removeDeptManager(DeptManager $deptManager): self
	{
		if ($this->deptManagers->removeElement($deptManager)) {
			// set the owning side to null (unless already changed)
			if ($deptManager->getEmpNo() === $this) {
				$deptManager->setEmpNo(null);
			}
		}

		return $this;
	}

}

src/Form/DeptEmpType.php
<?php

namespace App\Form;

use App\Entity\Department;
use App\Entity\DeptEmp;
use App\Entity\Employee;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type as FormType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class DeptEmpType extends AbstractType
{
	use BaseTypeTrait;
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
	        ->add('empNo', EntityType::class, [
		        'class' => Employee::class,
		        'choice_label' => function ($employee) {
			        return $employee->getFullName();
		        },
		        'choice_value' => 'empNo',
		        'label' => 'Employee',
		        'required' => true,
	        ])
	        ->add('deptNo', EntityType::class, [
		        'class' => Department::class,
		        'choice_label' => function ($department) {
			        return $department->getDeptName();
		        },
		        'choice_value' => 'deptNo',
		        'label' => 'Department',
		        'required' => true,
	        ])
	        ->add('fromDate',FormType\DateType::class,
		        [
			        'label' => 'Form date',
			        'required' => true,
			        'years' => $this->getPastYearsAndCurrent(),
			        'format' => 'y-M-d',
		        ])
	        ->add('toDate',FormType\DateType::class,
		        [
			        'label' => 'Form date',
			        'required' => true,
			        'years' => $this->getPastYearsAndCurrent(),
			        'format' => 'y-M-d',
		        ])
	        ->add('save',FormType\SubmitType::class, [
		        'label' => 'Save',
		        'attr' => array('class' => 'btn btn-primary btn-sm')
	        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DeptEmp::class,
        ]);
    }
}

src/Controller/DeptEmpController.php
<?php

namespace App\Controller;

use App\Entity\DeptEmp;
use App\Form\DeptEmpType;
use App\Repository\DeptEmpRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Routing\RouterInterface;

/**
 * @Route("/dept_emp")
 */
class DeptEmpController extends AbstractController
{

	private EntityManagerInterface $em;
	private RouterInterface $router;
	private FlashBagInterface $flashBag;
	private FormFactoryInterface $formFactory;

	public function __construct(
		EntityManagerInterface $em,
		RouterInterface $router,
		FormFactoryInterface $formFactory,
		FlashBagInterface $flashBag)
	{
		$this->em = $em;
		$this->router = $router;
		$this->flashBag = $flashBag;
		$this->formFactory = $formFactory;
	}

    /**
     * @Route("/", name="dept_emp_list", methods={"GET"})
     * @Security("is_granted('ROLE_USER')", message="Access denied")
     */
    public function listAction(Request $request): Response
    {
	    /** @var DeptEmpRepository $deptEmpRepository */
	    $deptEmpRepository = $this->em->getRepository(DeptEmp::class);
	    $deptEmps = $deptEmpRepository->findAll();

	    return $this->render('crud/dept_emp/list.html.twig', [
		    'dept_emps' => $deptEmps,
	    ]);
    }

    /**
     * @Route("/create", name="dept_emp_create", methods={"GET", "POST"})
     * @Security("is_granted('ROLE_USER')", message="Access denied")
     */
    public function createAction(Request $request): Response
    {
        $deptEmp = new DeptEmp();
        $form = $this->formFactory->create(DeptEmpType::class, $deptEmp);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
	        $this->em->persist($deptEmp);
	        $this->em->flush();
	        $this->flashBag->add('notice', 'Dept-Emp created');

            return $this->redirectToRoute('dept_emp_list', [], Response::HTTP_SEE_OTHER);
        }

	    return new Response(
		    $this->render(
			    'crud/dept_emp/create.html.twig',
			    ['form' => $form->createView()]
		    )
	    );
    }

    /**
     * @Route("/{id}", name="dept_emp_show", methods={"GET"})
     * @Security("is_granted('ROLE_USER')", message="Access denied")
     */
    public function showAction(DeptEmp $deptEmp): Response
    {
        return $this->render('crud/dept_emp/show.html.twig', [
            'dept_emp' => $deptEmp,
        ]);
    }

    /**
     * @Route("/{id}/update", name="dept_emp_update", methods={"GET", "POST"})
     * @Security("is_granted('ROLE_USER')", message="Access denied")
     */
    public function updateAction(Request $request, DeptEmp $deptEmp): Response
    {
        $form = $this->formFactory->create(DeptEmpType::class, $deptEmp);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
	        $this->em->persist($deptEmp);
	        $this->em->flush();
	        $this->flashBag->add('notice', 'Dept-Emp updated');

            return $this->redirectToRoute('dept_emp_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('crud/dept_emp/update.html.twig', [
            'dept_emp' => $deptEmp,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="dept_emp_delete")
     * @Security("is_granted('ROLE_USER')", message="Access denied")
     */
    public function deleteAction(DeptEmp $deptEmp): Response
    {
	    $this->em->remove($deptEmp);
	    $this->em->flush();

	    $this->flashBag->add('notice', 'Dept-emp was deleted');

	    return new RedirectResponse($this->router->generate('dept_emp_list'));
    }
}

templates/crud/dept_emp/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create DeptEmp{% endblock %}

{% block body %}

	<div class="d-block position-relative float-right mt-3 ">
		<a href="{{ path('dept_emp_list') }}" title="Create DeptEmp" class="btn btn-sm btn-secondary " disabled="disabled"><i class="fa fa-home"></i>
			Back</a>
	</div>
	<h6 class="border-bottom border-gray pb-2 mb-2 display-4">DeptEmp creat</h6>

	{{ form_start(form) }}
	<div class="form-group">
		{{ form_widget(form) }}
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/crud/dept_emp/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}DeptEmps{% endblock %}

{% block body %}
	<h6 class="display-4">DeptEmps</h6>
	{% for message in app.flashes('notice') %}
		<div class="alert alert-success">
			{{ message }}
		</div>
	{% endfor %}

    <table class="table" id="myTable">
        <thead>
            <tr>
                <th>Id</th>
                <th>FromDate</th>
                <th>ToDate</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for dept_emp in dept_emps %}
            <tr>
                <td>{{ dept_emp.id }}</td>
                <td>{{ dept_emp.fromDate ? dept_emp.fromDate|date('Y-m-d') : '' }}</td>
                <td>{{ dept_emp.toDate ? dept_emp.toDate|date('Y-m-d') : '' }}</td>
	            <td>
		            <a href="{{ path('dept_emp_show', {'id': dept_emp.id}) }}" class="btn btn-success btn-sm " role="button"
		               aria-pressed="true">Show</a>
		            <a href="{{ path('dept_emp_update', {'id': dept_emp.id}) }}" class="btn btn-warning btn-sm " role="button"
		               aria-pressed="true">Update</a>
		            <a href="{{ path('dept_emp_delete', {'id': dept_emp.id}) }}" class="btn btn-danger btn-sm " role="button"
		               aria-pressed="true">Delete</a>
	            </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
	<div class="d-flex">
		<div class="mr-auto p-2">
			<a href="{{ path('dept_emp_create') }}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Create new</a>
		</div>
	</div>
{% endblock %}
{% block javascripts %}

	{{ parent() }}

{% endblock %}

templates/crud/dept_emp/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}DeptEmp{% endblock %}

{% block body %}
	<div class="d-block position-relative float-right mt-3 ">
		<a href="{{ path('dept_emp_list') }}" title="Show DeptEmp" class="btn btn-sm btn-secondary " disabled="disabled"><i class="fa fa-home"></i>
			Back</a>
	</div>
	<h6 class="border-bottom border-gray pb-2 mb-2 display-4">DeptEmp show</h6>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ dept_emp.id }}</td>
            </tr>
            <tr>
                <th>FromDate</th>
                <td>{{ dept_emp.fromDate ? dept_emp.fromDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>ToDate</th>
                <td>{{ dept_emp.toDate ? dept_emp.toDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

	<div class="card-group py-2">
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">
					Employee name: {{ dept_emp.empNo.fullName }}
				</h5>
				<b>No: </b>{{ dept_emp.empNo.empNo }}<br>
				<b>Gender: </b>{{ dept_emp.empNo.gender|gender }}<br>
				<b>Birth date: </b>{{ dept_emp.empNo.birthDate ? dept_emp.empNo.birthDate|date('Y-m-d') : '' }}<br>
				<b>Hire date: </b>{{ dept_emp.empNo.hireDate ? dept_emp.empNo.hireDate|date('Y-m-d') : '' }}
			</div>
		</div>
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">
					Department name: {{ dept_emp.deptNo.deptName }}
				</h5>
				<b>No: </b>{{ dept_emp.deptNo.deptNo }}<br>
				<b>From: </b>{{ dept_emp.fromDate ? dept_emp.fromDate|date('Y-m-d') : '' }}<br>
				<b>To: </b>{{ dept_emp.toDate ? dept_emp.toDate|date('Y-m-d') : '' }}<br>
			</div>
		</div>
	</div>


{% endblock %}

templates/crud/dept_emp/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update DeptEmp{% endblock %}

{% block body %}
	<div class="d-block position-relative float-right mt-3 ">
		<a href="{{ path('dept_emp_list') }}" title="Update DeptEmp" class="btn btn-sm btn-secondary " disabled="disabled"><i class="fa fa-home"></i>
			Back</a>
	</div>
	<h6 class="border-bottom border-gray pb-2 mb-2 display-4">DeptEmp update</h6>

	{{ form_start(form) }}
	<div class="form-group">
		{{ form_widget(form) }}
	</div>
	{{ form_end(form) }}
{% endblock %}